spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  main:
    banner-mode: off
logging:
  level:
    com.zaxxer: WARN
    org.hibernate: WARN
    org.springframework: WARN
